language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican 
- pip3 git
- pip3 nodejs 
- pip3 npm 
- pip3 markdown
- npm install --global surge

script:
- pelican-quickstart
- pelican IC-WEB/index.md -s pelicanconf.py 

deploy:
  provider: surge
  project: ./output/
  domain: adriansilva.surge.sh
skip_cleanup: true
