language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican 
- pip3 install markdown

script:
- pelican content/ -s pelicanconf.py
- git add output/*
- git commit -m "Despliegue web"

deploy:
  provider: surge
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  project: ./output/
  domain: adriansilva.surge.sh
  on:
    branch: master
