language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican
- pip3 install markdown

script:
- git clone https://github.com/Adrian-SB/Web-estatica-elultimorecurso
- pelican IC-WEB/ -s Web-estatica-elultimorecurso/pelicanconf.py 

deploy:
  provider: surge
  project: ./output/
  domain: adriansilva.surge.sh
skip_cleanup: true
