language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican 
- pip3 install markdown
- pip3 install unzip
- pip3 install wget

script:
- wget https://github.com/onlyhavecans/pelican-chunk/archive/f9206df831d497688516cf86dd089004be1ee06a.zip
- unzip f9206df831d497688516cf86dd089004be1ee06a.zip  
- pelican IC-WEB/ -s .pelicanconf.py -t pelican-chunk-f9206df831d497688516cf86dd089004be1ee06a/
deploy:
  provider: surge
  project: ./output/
  domain: adriansilva.surge.sh
skip_cleanup: true
