language: python
branches:
  only:
  - master
  
python:
  - "3.6"
   
install:
- pip3 install pelican 
- pip3 install markdown

script:
- pelican content/ -s pelicanconf.py
- git add output/*
- git commit -m "Despliegue web"
- git config user.name "Adrian-SB"
- git config user.email "asboceta@gmail.com"
- git push origin master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  on:
    branch: master
